services:
  view:
    container_name: view
    build:
      context: ./view
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./view:/app
    command: ['sh', '-c', 'pnpm install && pnpm run dev']
    environment:
      NODE_ENV: development

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local